package com.mycompany.service.impl;

import com.mycompany.clases.DetalleVentas;
import com.mycompany.db.DBManager;
import com.mycompany.service.DetalleVentasService;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;

public class DetalleVentasServiceImpl implements DetalleVentasService {

	@Override
	public boolean addDetalleVentas(DetalleVentas detalleVentas) {
		boolean resultado = false;
		int autoGeneratedKeys = 0;
		String query = "insert into detalle_ventas (nom_prod,cantidad,prec_unit,prec_vent,cod_prod,id_ventas) "
				+ "values (?,?,?,?,?,?)";
		if (detalleVentas != null) {
			try (DBManager dbManager = new DBManager();
					PreparedStatement pStmt = dbManager.getConnection().prepareStatement(query, Statement.RETURN_GENERATED_KEYS);) {
				pStmt.setString(1, detalleVentas.getNom_prod());
				pStmt.setInt(2, detalleVentas.getCantidad());
				pStmt.setDouble(3, detalleVentas.getPrec_unit());
				pStmt.setDouble(4, detalleVentas.getPrec_vent());
				pStmt.setString(5, detalleVentas.getCod_prod());
				pStmt.setInt(6, detalleVentas.getId_ventas());
				int rowAffected = pStmt.executeUpdate();
			} catch (SQLException e) {
				while (e != null) {
					System.out.println("DetalleVentas Exception");
					System.out.println("SQLState: " + e.getSQLState());
					System.out.println("Error code: " + e.getErrorCode());
					System.out.println("Message: " + e.getMessage());
					Throwable t = e.getCause();
					while (t != null) {
						System.out.println("Cause: " + t);
						t = t.getCause();
					}
					e.getNextException();
				}
			}catch(Exception e){
				e.printStackTrace();
			}

		} else {
			System.out.println("Object DetalleVentas null (add)...");
		}
		return resultado;
	}

}
